name: Static Code Checks
run-name: code_checks
on: [push]
jobs:
  run-static_code_checks:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: 'Install requirements'
        run: pip install -r requirements.txt
      - name: 'Run typechecks'
        run: tox
